spring.application.name=reservation-service
server.port=9094

# Database - DEDICATED DB for reservation service
spring.datasource.url=jdbc:mysql://localhost:3306/reservation_db
spring.datasource.username=root
spring.datasource.password=root
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false
spring.jpa.show-sql=true



# Swagger
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.api-docs.path=/api-docs

# Actuators
management.endpoints.web.exposure.include=*
management.endpoint.health.show-details=always
management.info.env.enabled=true

# App info
info.app.name=Vehicle Parking Management System
info.app.version=1.0.0
info.app.developer=Lokesh Gandham
info.app.description=REST API for managing vehicle parking reservations

# Eureka
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true
eureka.instance.prefer-ip-address=true
eureka.instance.hostname=localhost
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/

# Feign
spring.cloud.openfeign.okhttp.enabled=true
feign.circuitbreaker.enabled=true
spring.cloud.openfeign.circuitbreaker.enabled=true

# Resilience4j - slotManagement-service
resilience4j.circuitbreaker.instances.slotManagement-service.sliding-window-size=10
resilience4j.circuitbreaker.instances.slotManagement-service.failure-rate-threshold=50
resilience4j.circuitbreaker.instances.slotManagement-service.wait-duration-in-open-state=10s
resilience4j.circuitbreaker.instances.slotManagement-service.permitted-number-of-calls-in-half-open-state=3
resilience4j.circuitbreaker.instances.slotManagement-service.automatic-transition-from-open-to-half-open-enabled=true
resilience4j.circuitbreaker.instances.slotManagement-service.record-exceptions=java.lang.Exception

# Resilience4j - USER-SERVICE
resilience4j.circuitbreaker.instances.USER-SERVICE.sliding-window-size=10
resilience4j.circuitbreaker.instances.USER-SERVICE.failure-rate-threshold=50
resilience4j.circuitbreaker.instances.USER-SERVICE.wait-duration-in-open-state=10s
resilience4j.circuitbreaker.instances.USER-SERVICE.permitted-number-of-calls-in-half-open-state=3
resilience4j.circuitbreaker.instances.USER-SERVICE.automatic-transition-from-open-to-half-open-enabled=true
resilience4j.circuitbreaker.instances.USER-SERVICE.record-exceptions=java.lang.Exception

# Logging handled by logback-spring.xml