# ?? Application ???????????????????????????????????????????????????????????????
spring.application.name=vehicleLog-service

# ?? Server ????????????????????????????????????????????????????????????????????
server.port=9093

# ?? Database ??????????????????????????????????????????????????????????????????
spring.datasource.url=jdbc:mysql://localhost:3306/vehicle_log_db
spring.datasource.username=root
spring.datasource.password=root
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.open-in-view=false


# ?? Eureka ????????????????????????????????????????????????????????????????????
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true
eureka.instance.prefer-ip-address=true
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/

# ?? Feign ?????????????????????????????????????????????????????????????????????
spring.cloud.openfeign.okhttp.enabled=true
spring.cloud.openfeign.circuitbreaker.enabled=true
feign.client.user-service=USERMODULE
feign.client.slot-service=SLOT-MANAGEMENT-SERVICE
feign.client.reservation-service=RESERVATION-SERVICE


# ?? Resilience4j ? ParkingSlotClient ?????????????????????????????????????????
resilience4j.circuitbreaker.instances.ParkingSlotClient.register-health-indicator=true
resilience4j.circuitbreaker.instances.ParkingSlotClient.sliding-window-size=5
resilience4j.circuitbreaker.instances.ParkingSlotClient.failure-rate-threshold=50
resilience4j.circuitbreaker.instances.ParkingSlotClient.wait-duration-in-open-state=10s
resilience4j.circuitbreaker.instances.ParkingSlotClient.permitted-number-of-calls-in-half-open-state=2

# ?? Resilience4j ? UserClient ?????????????????????????????????????????????????
resilience4j.circuitbreaker.instances.UserClient.register-health-indicator=true
resilience4j.circuitbreaker.instances.UserClient.sliding-window-size=5
resilience4j.circuitbreaker.instances.UserClient.failure-rate-threshold=50
resilience4j.circuitbreaker.instances.UserClient.wait-duration-in-open-state=10s
resilience4j.circuitbreaker.instances.UserClient.permitted-number-of-calls-in-half-open-state=2

# ?? Swagger / OpenAPI ?????????????????????????????????????????????????????????
springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.operationsSorter=method

# ?? Logging ???????????????????????????????????????????????????????????????????
logging.level.com.cts.project.vpms.vehiclelog.client=DEBUG