spring.application.name=invoice-service
server.port=9095

# MySQL
spring.datasource.url=jdbc:mysql://localhost:3306/invoice_db
spring.datasource.username=root
spring.datasource.password=root
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.open-in-view=false

# Eureka ? register invoice service so gateway and other services can find it
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true
eureka.instance.prefer-ip-address=true
eureka.instance.hostname=localhost
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/

# Swagger
springdoc.api-docs.enabled=true
springdoc.swagger-ui.enabled=true
springdoc.swagger-ui.path=/swagger-ui.html

# UPI Billing
billing.upi.vpa=prasanthred53@oksbi
billing.upi.name=VPMS

# JWT
jwt.secret=3b0a560c5c4ad48f09d73723e9e74fd095eeb40173c4ccd5b72ef4afe0789dc6
jwt.expiration-ms=86400000

spring.mvc.favicon.enabled=false